
package com.uni.gc.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentSoapService", targetNamespace = "http://gc.uni.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentSoapService {


    /**
     * 
     * @param studentId
     * @return
     *     returns com.uni.gc.client.StudentDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchStudentById", targetNamespace = "http://gc.uni.com/", className = "com.uni.gc.client.SearchStudentById")
    @ResponseWrapper(localName = "searchStudentByIdResponse", targetNamespace = "http://gc.uni.com/", className = "com.uni.gc.client.SearchStudentByIdResponse")
    public StudentDTO searchStudentById(
        @WebParam(name = "studentId", targetNamespace = "")
        Integer studentId);

}
